services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animatica
    networks:
      - animatica-net
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  api:
    container_name: api
    build:
      context: app/
      args:
        BUILD_MODE: development
    volumes:
      - ./app:/app
    restart: always
    ports:
      - "8080:80"
    networks:
      - animatica-net
    env_file:
      - env/api.env
      - env/auth.env
      - env/db.env
      - env/ml.env
      - env/stripe.env
    depends_on:
      - db

volumes:
  pg_data:

networks:
  animatica-net:
    driver: bridge
