"""Added stripe_link to SubscriptionType

Revision ID: 6dc4ea54e990
Revises: 91b40a6a7ccf
Create Date: 2025-04-01 09:42:35.809002

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dc4ea54e990"
down_revision: Union[str, None] = "91b40a6a7ccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription_type", sa.Column("stripe_link", sa.String(), nullable=True))
    op.create_unique_constraint(None, "subscription_type", ["stripe_link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscription_type", type_="unique")
    op.drop_column("subscription_type", "stripe_link")
    # ### end Alembic commands ###
