"""Simplified the DB schema by deleting subscription tables

Revision ID: 93ced1d205a8
Revises: 6dc4ea54e990
Create Date: 2025-04-11 17:47:36.547581

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93ced1d205a8"
down_revision: Union[str, None] = "6dc4ea54e990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("remaining_queries", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("subscription_type_features")
    op.drop_table("subscription_feature")
    op.drop_table("user_subscription")
    op.drop_table("subscription_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_feature",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('subscription_feature_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="subscription_feature_pkey"),
        sa.UniqueConstraint("description", name="subscription_feature_description_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "subscription_type",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            postgresql.ENUM("BASIC", "STANDARD", "PREMIUM", "TRIAL", "EXPIRED", name="subscriptiontypeenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("price", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("discount", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column("total_credits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("duration_days", sa.INTEGER(), autoincrement=False, nullable=True, comment="Duration in days"),
        sa.Column("stripe_link", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="subscription_type_pkey"),
        sa.UniqueConstraint("name", name="subscription_type_name_key"),
        sa.UniqueConstraint("stripe_link", name="subscription_type_stripe_link_key"),
    )
    op.create_table(
        "subscription_type_features",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("subscription_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("subscription_feature_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_feature_id"],
            ["subscription_feature.id"],
            name="subscription_type_features_subscription_feature_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_type_id"],
            ["subscription_type.id"],
            name="subscription_type_features_subscription_type_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="subscription_type_features_pkey"),
    )
    op.create_table(
        "user_subscription",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("subscription_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("remaining_credits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("expired_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_type_id"], ["subscription_type.id"], name="user_subscription_subscription_type_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_subscription_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="user_subscription_pkey"),
    )

    op.drop_table("subscription")
    # ### end Alembic commands ###
