"""Extended subscriptions tables

Revision ID: d39146a59f9c
Revises: 3632c608b4ab
Create Date: 2025-03-31 20:22:04.916276

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d39146a59f9c"
down_revision: Union[str, None] = "3632c608b4ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription_type", sa.Column("total_credits", sa.Integer(), nullable=True))
    op.add_column(
        "subscription_type", sa.Column("duration_days", sa.Integer(), nullable=True, comment="Duration in days")
    )
    op.alter_column(
        "subscription_type", "price", existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=False
    )
    op.alter_column(
        "subscription_type", "discount", existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=True
    )
    op.add_column("user_subscription", sa.Column("remaining_credits", sa.Integer(), nullable=True))
    op.add_column("user_subscription", sa.Column("expired_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_subscription", "expired_at")
    op.drop_column("user_subscription", "remaining_credits")
    op.alter_column(
        "subscription_type", "discount", existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "subscription_type", "price", existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=False
    )
    op.drop_column("subscription_type", "duration_days")
    op.drop_column("subscription_type", "total_credits")
    # ### end Alembic commands ###
