"""Updated tables for subscriptions

Revision ID: 3632c608b4ab
Revises: bced652ab008
Create Date: 2025-03-31 18:18:43.878327

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3632c608b4ab"
down_revision: Union[str, None] = "bced652ab008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscription",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subscription_type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_type_id"],
            ["subscription_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("subscription")
    op.add_column("subscription_type", sa.Column("price", sa.Float(precision=2), nullable=False))
    op.add_column("subscription_type", sa.Column("discount", sa.Float(precision=2), nullable=True))
    op.add_column("subscription_type", sa.Column("currency", sa.String(length=3), nullable=False))
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.drop_column("subscription_type", "currency")
    op.drop_column("subscription_type", "discount")
    op.drop_column("subscription_type", "price")
    op.create_table(
        "subscription",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("subscription_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_type_id"], ["subscription_type.id"], name="subscription_subscription_type_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="subscription_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="subscription_pkey"),
    )
    op.drop_table("user_subscription")
    # ### end Alembic commands ###
