"""Added constraits for subscriptions

Revision ID: 91b40a6a7ccf
Revises: d39146a59f9c
Create Date: 2025-03-31 20:48:57.344451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91b40a6a7ccf"
down_revision: Union[str, None] = "d39146a59f9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription_type", "price", existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=False
    )
    op.alter_column(
        "subscription_type", "discount", existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription_type", "discount", existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "subscription_type", "price", existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=False
    )
    # ### end Alembic commands ###
