name: Lint

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: isort
        uses: isort/isort-action@master
        with:
          requirementsFiles: "app/requirements.txt"
          sortPaths: app/
      - name: black
        uses: psf/black@stable
